/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.BerandaController;
import controller.EditController;
import controller.HapusController;
import controller.TambahController;
import java.awt.Color;
//import java.sql.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import model.Reservasi;
import model.tableModelReservasi;

/**
 *
 * @author ASUS
 */
public class Beranda extends javax.swing.JFrame {

    BerandaController cBeranda;
    TambahController cTambah;
    EditController cEdit;
    HapusController cHapus;
    
    Reservasi reservasi = new Reservasi();
    private int id;
    public Beranda() {
        initComponents();
        cBeranda = new BerandaController(this);
        cTambah = new TambahController(this);
        cEdit = new EditController(this);
        cHapus = new HapusController(this);
        cBeranda.load_table();
        Color col= new Color(194, 217, 255);
        getContentPane().setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipeKamar = new javax.swing.JComboBox<>();
        noKamar = new javax.swing.JTextField();
        tipePembayaran = new javax.swing.JComboBox<>();
        totalHargaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        informasi = new javax.swing.JButton();
        tanggalMasuk = new com.toedter.calendar.JDateChooser();
        tanggalKeluar = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jumlahPelanggan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(142, 143, 250));

        jLabel1.setBackground(new java.awt.Color(25, 4, 130));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESERVEMATE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(642, 642, 642))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("jPanel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama Pelanggan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tipe Kamar");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tanggal Masuk");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tanggal Keluar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tipe Pembayaran");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Harga");

        namaPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("No Kamar");

        tipeKamar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipeKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standar", "VIP", "Superior", "Deluxe" }));
        tipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipeKamarActionPerformed(evt);
            }
        });

        noKamar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tipePembayaran.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Non Tunai" }));
        tipePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipePembayaranActionPerformed(evt);
            }
        });

        totalHargaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalHargaLabel.setText("0");

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pelanggan", "No HP", "Jumlah Pelanggan", "Tipe Kamar", "No Kamar", "Tanggal Masuk", "Tanggal Keluar", "Harga", "Tipe Pembayaran"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);

        edit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reset.setText("RESET");

        tambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tambah.setText("TAMBAH DATA");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        informasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        informasi.setText("INFORMASi KAMAR");
        informasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informasiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("No HP");

        nohp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Jumlah Pelanggan");

        jumlahPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(reset)
                        .addGap(18, 18, 18)
                        .addComponent(informasi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaPelanggan)
                            .addComponent(tipeKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noKamar)
                            .addComponent(tipePembayaran, 0, 224, Short.MAX_VALUE)
                            .addComponent(tanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggalKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nohp)
                            .addComponent(jumlahPelanggan)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalHargaLabel)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jumlahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(noKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalHargaLabel)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tipePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit)
                            .addComponent(delete)
                            .addComponent(reset)
                            .addComponent(informasi))
                        .addGap(18, 18, 18)
                        .addComponent(tambah)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabelPelanggan(){
        return tabelPelanggan;
    }
    
    public JTextField getTxtNamaPelanggan(){
        return namaPelanggan;
    }
    
    public JTextField getTxtNohp(){
        return nohp;
    }
    
    public JTextField getTxtJumlahPelanggan(){
        return jumlahPelanggan;
    }
    
    public JComboBox getCbTipeKamar(){
        return tipeKamar;
    }
    
    public JTextField getTxtNoKamar(){
        return noKamar;
    }
    
    public JDateChooser getDtTanggalMasuk(){
        return tanggalMasuk;
    }
    
    public JDateChooser getDtTanggalKeluar(){
        return tanggalKeluar;
    }
    
    public JLabel getLabelTotalharga(){
        return totalHargaLabel;
    }
    
    public JComboBox getCbTipePembayaran(){
        return tipePembayaran;
    }
    
    public void setTxtNamaPelanggan(String NamaPelanggan){
        namaPelanggan.setText(NamaPelanggan);
    }
    
    public void setTxtNohp(String NoHp){
        nohp.setText(NoHp);
    }
    
    public void setTxtJumlahPelanggan(String JumlahPelanggan){
        jumlahPelanggan.setText(JumlahPelanggan);
    }
    
    public void setCbTipeKamar(String TipeKamar){
        tipeKamar.setSelectedItem(TipeKamar);
    }
    
    public void setTxtNoKamar(String NoKamar){
        noKamar.setText(NoKamar);
    }
    
    public void setDtTanggalMasuk(Date TanggalMasuk){
        tanggalMasuk.setDate(TanggalMasuk);
    }
    
    public void setDtTanggalKeluar(Date TanggalKeluar){
        tanggalKeluar.setDate(TanggalKeluar);
    }
    
    public void setLabelTotalharga(){   
        Date tanggalMasuk = this.tanggalMasuk.getDate();
        Date tanggalKeluar = this.tanggalKeluar.getDate();

        if (tanggalMasuk != null && tanggalKeluar != null) {
            long selisihMillis = tanggalKeluar.getTime() - tanggalMasuk.getTime();
            int selisihHari = (int) (selisihMillis / (24 * 60 * 60 * 1000));

            String tipeKamarTerpilih = tipeKamar.getSelectedItem().toString();
            int harga = 0;

            if (tipeKamarTerpilih.equals("Standar")) {
                harga = 100000;
            } else if (tipeKamarTerpilih.equals("VIP")) {
                harga = 200000;
            } else if (tipeKamarTerpilih.equals("Superior")) {
                harga = 300000;
            } else if (tipeKamarTerpilih.equals("Deluxe")) {
                harga = 400000;
            }

            int totalHarga = harga * selisihHari;
            totalHargaLabel.setText(Integer.toString(totalHarga));

        }
    }
    
    public void setCbTipePembayaran(String TipePemabayaran){
        tipePembayaran.setSelectedItem(TipePemabayaran);
    }
    private void tipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeKamarActionPerformed
        setLabelTotalharga();
    }//GEN-LAST:event_tipeKamarActionPerformed

    private void tipePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipePembayaranActionPerformed
        setLabelTotalharga();
    }//GEN-LAST:event_tipePembayaranActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        cEdit.simpan_edit(this.id);
        cBeranda.load_table();
    }//GEN-LAST:event_editActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        cTambah.tambah_data();
        cBeranda.load_table();
    }//GEN-LAST:event_tambahActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        cHapus.hapus(this.id);
        cBeranda.load_table();
    }//GEN-LAST:event_deleteActionPerformed

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        int selectedRow = tabelPelanggan.getSelectedRow();
        // Make sure a row is selected
        if (selectedRow != -1) {
            tableModelReservasi model = (tableModelReservasi) tabelPelanggan.getModel();

            // Assuming id is at index 0
            this.id = (int) model.getValueAt(selectedRow, 0);
            
            namaPelanggan.setText((String) model.getValueAt(selectedRow, 1));
            nohp.setText((String) model.getValueAt(selectedRow, 2));
            jumlahPelanggan.setText(String.valueOf(model.getValueAt(selectedRow, 3)));
            tipeKamar.setSelectedItem((String) model.getValueAt(selectedRow, 4));
            noKamar.setText(String.valueOf(model.getValueAt(selectedRow, 5)));
            String dateString = (String) model.getValueAt(selectedRow, 6);
            String dateString1 = (String) model.getValueAt(selectedRow, 7);
            totalHargaLabel.setText(String.valueOf(model.getValueAt(selectedRow, 8)));
            tipePembayaran.setSelectedItem((String) model.getValueAt(selectedRow, 9));
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date parsedDate = dateFormat.parse(dateString);
                Date parsedDate1 = dateFormat.parse(dateString1);
                tanggalMasuk.setDate(parsedDate);
                tanggalKeluar.setDate(parsedDate1);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void informasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informasiActionPerformed
       cBeranda.showInformasiKamar();
    }//GEN-LAST:event_informasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton informasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahPelanggan;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField noKamar;
    private javax.swing.JTextField nohp;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tanggalKeluar;
    private com.toedter.calendar.JDateChooser tanggalMasuk;
    private javax.swing.JComboBox<String> tipeKamar;
    private javax.swing.JComboBox<String> tipePembayaran;
    private javax.swing.JLabel totalHargaLabel;
    // End of variables declaration//GEN-END:variables
}
