    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import model.Reservasi;

/**
 *
 * @author ASUS
 */
public class InformasiKamar extends javax.swing.JFrame {

    /**
     * Creates new form InformasiKamar
     */
    private final List<Reservasi> listReservasi;
    
    public InformasiKamar(List<Reservasi> listReservasi) {
        initComponents();
        this.listReservasi = listReservasi;
        Color col= new Color(194, 217, 255);
        getContentPane().setBackground(col);
        updateUI();
    }
    
    private void updateUI() {
        for (Reservasi reservasi : listReservasi) {
            int noKamar = reservasi.getNoKamar();
            String panelName = "kamar" + noKamar;

            changePanelColorToRed(panelName);
        }
    }
    
    private void changePanelColorToRed(String panelName) {
        JPanel panel = null;

        try {
            java.lang.reflect.Field field = getClass().getDeclaredField(panelName);
            panel = (JPanel) field.get(this);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }

        if (panel != null) {
            panel.setBackground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kamar101 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        kamar102 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        kamar103 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        kamar104 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        kamar107 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        kamar105 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        kamar108 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        kamar106 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        kamar109 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kamar301 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        kamar302 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        kamar303 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        kamar304 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        kamar305 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        kamar306 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        kamar307 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        kamar308 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        kamar309 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kamar201 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        kamar202 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        kamar203 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kamar204 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        kamar205 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        kamar206 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        kamar207 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        kamar208 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        kamar209 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        kamar407 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        kamar408 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        kamar409 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kamar401 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        kamar402 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        kamar403 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        kamar404 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        kamar405 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        kamar406 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(142, 143, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("RESERVEMATE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(614, 614, 614))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("INFORMASI KETERSEDIAN KAMAR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Kamar Standar");

        kamar101.setBackground(new java.awt.Color(167, 211, 151));

        jLabel7.setText("101");

        javax.swing.GroupLayout kamar101Layout = new javax.swing.GroupLayout(kamar101);
        kamar101.setLayout(kamar101Layout);
        kamar101Layout.setHorizontalGroup(
            kamar101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar101Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        kamar101Layout.setVerticalGroup(
            kamar101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar101Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kamar102.setBackground(new java.awt.Color(167, 211, 151));

        jLabel8.setText("102");

        javax.swing.GroupLayout kamar102Layout = new javax.swing.GroupLayout(kamar102);
        kamar102.setLayout(kamar102Layout);
        kamar102Layout.setHorizontalGroup(
            kamar102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar102Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        kamar102Layout.setVerticalGroup(
            kamar102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar102Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar103.setBackground(new java.awt.Color(167, 211, 151));

        jLabel9.setText("103");

        javax.swing.GroupLayout kamar103Layout = new javax.swing.GroupLayout(kamar103);
        kamar103.setLayout(kamar103Layout);
        kamar103Layout.setHorizontalGroup(
            kamar103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar103Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        kamar103Layout.setVerticalGroup(
            kamar103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar103Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kamar104.setBackground(new java.awt.Color(167, 211, 151));

        jLabel10.setText("104");

        javax.swing.GroupLayout kamar104Layout = new javax.swing.GroupLayout(kamar104);
        kamar104.setLayout(kamar104Layout);
        kamar104Layout.setHorizontalGroup(
            kamar104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar104Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kamar104Layout.setVerticalGroup(
            kamar104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar104Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        kamar107.setBackground(new java.awt.Color(167, 211, 151));

        jLabel13.setText("107");

        javax.swing.GroupLayout kamar107Layout = new javax.swing.GroupLayout(kamar107);
        kamar107.setLayout(kamar107Layout);
        kamar107Layout.setHorizontalGroup(
            kamar107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar107Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        kamar107Layout.setVerticalGroup(
            kamar107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar107Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar105.setBackground(new java.awt.Color(167, 211, 151));

        jLabel11.setText("105");

        javax.swing.GroupLayout kamar105Layout = new javax.swing.GroupLayout(kamar105);
        kamar105.setLayout(kamar105Layout);
        kamar105Layout.setHorizontalGroup(
            kamar105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar105Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        kamar105Layout.setVerticalGroup(
            kamar105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar105Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar108.setBackground(new java.awt.Color(167, 211, 151));

        jLabel14.setText("108");

        javax.swing.GroupLayout kamar108Layout = new javax.swing.GroupLayout(kamar108);
        kamar108.setLayout(kamar108Layout);
        kamar108Layout.setHorizontalGroup(
            kamar108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar108Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        kamar108Layout.setVerticalGroup(
            kamar108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar108Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar106.setBackground(new java.awt.Color(167, 211, 151));

        jLabel12.setText("106");

        javax.swing.GroupLayout kamar106Layout = new javax.swing.GroupLayout(kamar106);
        kamar106.setLayout(kamar106Layout);
        kamar106Layout.setHorizontalGroup(
            kamar106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar106Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        kamar106Layout.setVerticalGroup(
            kamar106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar106Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar109.setBackground(new java.awt.Color(167, 211, 151));

        jLabel15.setText("109");

        javax.swing.GroupLayout kamar109Layout = new javax.swing.GroupLayout(kamar109);
        kamar109.setLayout(kamar109Layout);
        kamar109Layout.setHorizontalGroup(
            kamar109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar109Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        kamar109Layout.setVerticalGroup(
            kamar109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar109Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Kamar Deluxe");

        kamar301.setBackground(new java.awt.Color(167, 211, 151));

        jLabel25.setText("301");

        javax.swing.GroupLayout kamar301Layout = new javax.swing.GroupLayout(kamar301);
        kamar301.setLayout(kamar301Layout);
        kamar301Layout.setHorizontalGroup(
            kamar301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar301Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        kamar301Layout.setVerticalGroup(
            kamar301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar301Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar302.setBackground(new java.awt.Color(167, 211, 151));

        jLabel26.setText("302");

        javax.swing.GroupLayout kamar302Layout = new javax.swing.GroupLayout(kamar302);
        kamar302.setLayout(kamar302Layout);
        kamar302Layout.setHorizontalGroup(
            kamar302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar302Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );
        kamar302Layout.setVerticalGroup(
            kamar302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar302Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar303.setBackground(new java.awt.Color(167, 211, 151));

        jLabel27.setText("303");

        javax.swing.GroupLayout kamar303Layout = new javax.swing.GroupLayout(kamar303);
        kamar303.setLayout(kamar303Layout);
        kamar303Layout.setHorizontalGroup(
            kamar303Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar303Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
        );
        kamar303Layout.setVerticalGroup(
            kamar303Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar303Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar304.setBackground(new java.awt.Color(167, 211, 151));

        jLabel28.setText("304");

        javax.swing.GroupLayout kamar304Layout = new javax.swing.GroupLayout(kamar304);
        kamar304.setLayout(kamar304Layout);
        kamar304Layout.setHorizontalGroup(
            kamar304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar304Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap())
        );
        kamar304Layout.setVerticalGroup(
            kamar304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar304Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar305.setBackground(new java.awt.Color(167, 211, 151));

        jLabel29.setText("305");

        javax.swing.GroupLayout kamar305Layout = new javax.swing.GroupLayout(kamar305);
        kamar305.setLayout(kamar305Layout);
        kamar305Layout.setHorizontalGroup(
            kamar305Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar305Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
        );
        kamar305Layout.setVerticalGroup(
            kamar305Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar305Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar306.setBackground(new java.awt.Color(167, 211, 151));

        jLabel30.setText("306");

        javax.swing.GroupLayout kamar306Layout = new javax.swing.GroupLayout(kamar306);
        kamar306.setLayout(kamar306Layout);
        kamar306Layout.setHorizontalGroup(
            kamar306Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar306Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );
        kamar306Layout.setVerticalGroup(
            kamar306Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar306Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar307.setBackground(new java.awt.Color(167, 211, 151));

        jLabel31.setText("307");

        javax.swing.GroupLayout kamar307Layout = new javax.swing.GroupLayout(kamar307);
        kamar307.setLayout(kamar307Layout);
        kamar307Layout.setHorizontalGroup(
            kamar307Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar307Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addContainerGap())
        );
        kamar307Layout.setVerticalGroup(
            kamar307Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar307Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar308.setBackground(new java.awt.Color(167, 211, 151));

        jLabel32.setText("308");

        javax.swing.GroupLayout kamar308Layout = new javax.swing.GroupLayout(kamar308);
        kamar308.setLayout(kamar308Layout);
        kamar308Layout.setHorizontalGroup(
            kamar308Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar308Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
        );
        kamar308Layout.setVerticalGroup(
            kamar308Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar308Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar309.setBackground(new java.awt.Color(167, 211, 151));

        jLabel33.setText("309");

        javax.swing.GroupLayout kamar309Layout = new javax.swing.GroupLayout(kamar309);
        kamar309.setLayout(kamar309Layout);
        kamar309Layout.setHorizontalGroup(
            kamar309Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar309Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addContainerGap())
        );
        kamar309Layout.setVerticalGroup(
            kamar309Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar309Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Kamar Superior");

        kamar201.setBackground(new java.awt.Color(167, 211, 151));

        jLabel16.setText("201");

        javax.swing.GroupLayout kamar201Layout = new javax.swing.GroupLayout(kamar201);
        kamar201.setLayout(kamar201Layout);
        kamar201Layout.setHorizontalGroup(
            kamar201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar201Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        kamar201Layout.setVerticalGroup(
            kamar201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar201Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar202.setBackground(new java.awt.Color(167, 211, 151));

        jLabel17.setText("202");

        javax.swing.GroupLayout kamar202Layout = new javax.swing.GroupLayout(kamar202);
        kamar202.setLayout(kamar202Layout);
        kamar202Layout.setHorizontalGroup(
            kamar202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar202Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        kamar202Layout.setVerticalGroup(
            kamar202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar202Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar203.setBackground(new java.awt.Color(167, 211, 151));

        jLabel18.setText("203");

        javax.swing.GroupLayout kamar203Layout = new javax.swing.GroupLayout(kamar203);
        kamar203.setLayout(kamar203Layout);
        kamar203Layout.setHorizontalGroup(
            kamar203Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar203Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        kamar203Layout.setVerticalGroup(
            kamar203Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar203Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar204.setBackground(new java.awt.Color(167, 211, 151));

        jLabel19.setText("204");

        javax.swing.GroupLayout kamar204Layout = new javax.swing.GroupLayout(kamar204);
        kamar204.setLayout(kamar204Layout);
        kamar204Layout.setHorizontalGroup(
            kamar204Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar204Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        kamar204Layout.setVerticalGroup(
            kamar204Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar204Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar205.setBackground(new java.awt.Color(167, 211, 151));

        jLabel20.setText("205");

        javax.swing.GroupLayout kamar205Layout = new javax.swing.GroupLayout(kamar205);
        kamar205.setLayout(kamar205Layout);
        kamar205Layout.setHorizontalGroup(
            kamar205Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar205Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        kamar205Layout.setVerticalGroup(
            kamar205Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar205Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar206.setBackground(new java.awt.Color(167, 211, 151));

        jLabel21.setText("206");

        javax.swing.GroupLayout kamar206Layout = new javax.swing.GroupLayout(kamar206);
        kamar206.setLayout(kamar206Layout);
        kamar206Layout.setHorizontalGroup(
            kamar206Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar206Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );
        kamar206Layout.setVerticalGroup(
            kamar206Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar206Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar207.setBackground(new java.awt.Color(167, 211, 151));

        jLabel22.setText("207");

        javax.swing.GroupLayout kamar207Layout = new javax.swing.GroupLayout(kamar207);
        kamar207.setLayout(kamar207Layout);
        kamar207Layout.setHorizontalGroup(
            kamar207Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar207Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );
        kamar207Layout.setVerticalGroup(
            kamar207Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar207Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar208.setBackground(new java.awt.Color(167, 211, 151));

        jLabel23.setText("208");

        javax.swing.GroupLayout kamar208Layout = new javax.swing.GroupLayout(kamar208);
        kamar208.setLayout(kamar208Layout);
        kamar208Layout.setHorizontalGroup(
            kamar208Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar208Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );
        kamar208Layout.setVerticalGroup(
            kamar208Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar208Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar209.setBackground(new java.awt.Color(167, 211, 151));

        jLabel24.setText("209");

        javax.swing.GroupLayout kamar209Layout = new javax.swing.GroupLayout(kamar209);
        kamar209.setLayout(kamar209Layout);
        kamar209Layout.setHorizontalGroup(
            kamar209Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar209Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap())
        );
        kamar209Layout.setVerticalGroup(
            kamar209Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar209Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar407.setBackground(new java.awt.Color(167, 211, 151));

        jLabel40.setText("407");

        javax.swing.GroupLayout kamar407Layout = new javax.swing.GroupLayout(kamar407);
        kamar407.setLayout(kamar407Layout);
        kamar407Layout.setHorizontalGroup(
            kamar407Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar407Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addContainerGap())
        );
        kamar407Layout.setVerticalGroup(
            kamar407Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar407Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar408.setBackground(new java.awt.Color(167, 211, 151));

        jLabel41.setText("408");

        javax.swing.GroupLayout kamar408Layout = new javax.swing.GroupLayout(kamar408);
        kamar408.setLayout(kamar408Layout);
        kamar408Layout.setHorizontalGroup(
            kamar408Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar408Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addContainerGap())
        );
        kamar408Layout.setVerticalGroup(
            kamar408Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar408Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar409.setBackground(new java.awt.Color(167, 211, 151));

        jLabel42.setText("409");

        javax.swing.GroupLayout kamar409Layout = new javax.swing.GroupLayout(kamar409);
        kamar409.setLayout(kamar409Layout);
        kamar409Layout.setHorizontalGroup(
            kamar409Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar409Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addContainerGap())
        );
        kamar409Layout.setVerticalGroup(
            kamar409Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar409Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Kamar VIP");

        kamar401.setBackground(new java.awt.Color(167, 211, 151));

        jLabel34.setText("401");

        javax.swing.GroupLayout kamar401Layout = new javax.swing.GroupLayout(kamar401);
        kamar401.setLayout(kamar401Layout);
        kamar401Layout.setHorizontalGroup(
            kamar401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar401Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addContainerGap())
        );
        kamar401Layout.setVerticalGroup(
            kamar401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar401Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar402.setBackground(new java.awt.Color(167, 211, 151));

        jLabel35.setText("402");

        javax.swing.GroupLayout kamar402Layout = new javax.swing.GroupLayout(kamar402);
        kamar402.setLayout(kamar402Layout);
        kamar402Layout.setHorizontalGroup(
            kamar402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar402Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addContainerGap())
        );
        kamar402Layout.setVerticalGroup(
            kamar402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar402Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar403.setBackground(new java.awt.Color(167, 211, 151));

        jLabel36.setText("403");

        javax.swing.GroupLayout kamar403Layout = new javax.swing.GroupLayout(kamar403);
        kamar403.setLayout(kamar403Layout);
        kamar403Layout.setHorizontalGroup(
            kamar403Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar403Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addContainerGap())
        );
        kamar403Layout.setVerticalGroup(
            kamar403Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar403Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar404.setBackground(new java.awt.Color(167, 211, 151));

        jLabel37.setText("404");

        javax.swing.GroupLayout kamar404Layout = new javax.swing.GroupLayout(kamar404);
        kamar404.setLayout(kamar404Layout);
        kamar404Layout.setHorizontalGroup(
            kamar404Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar404Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addContainerGap())
        );
        kamar404Layout.setVerticalGroup(
            kamar404Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar404Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar405.setBackground(new java.awt.Color(167, 211, 151));

        jLabel38.setText("405");

        javax.swing.GroupLayout kamar405Layout = new javax.swing.GroupLayout(kamar405);
        kamar405.setLayout(kamar405Layout);
        kamar405Layout.setHorizontalGroup(
            kamar405Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar405Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );
        kamar405Layout.setVerticalGroup(
            kamar405Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar405Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        kamar406.setBackground(new java.awt.Color(167, 211, 151));

        jLabel39.setText("406");

        javax.swing.GroupLayout kamar406Layout = new javax.swing.GroupLayout(kamar406);
        kamar406.setLayout(kamar406Layout);
        kamar406Layout.setHorizontalGroup(
            kamar406Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kamar406Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addContainerGap())
        );
        kamar406Layout.setVerticalGroup(
            kamar406Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamar406Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Kembali Ke Beranda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(543, 543, 543))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kamar101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(kamar104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kamar107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar205, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar207, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar208, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar206, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar209, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kamar201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kamar301, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar305, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar307, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar308, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar306, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar407, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar408, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kamar404, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamar405, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar409, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar406, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kamar401, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar402, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar403, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(180, 180, 180))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kamar301, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamar302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamar303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kamar306, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar305, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar308, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar307, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar205, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(kamar206, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kamar208, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamar207, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamar209, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kamar401, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamar402, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamar403, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kamar406, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kamar409, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar405, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar404, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamar408, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamar407, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kamar102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kamar103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kamar101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kamar105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kamar104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kamar106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kamar108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kamar107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kamar109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Set the Nimbus look and feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformasiKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Create an instance of InformasiKamar with the listReservasi argument
                List<Reservasi> listReservasi = new ArrayList<>(); // Replace this with your actual data
                new InformasiKamar(listReservasi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel kamar101;
    private javax.swing.JPanel kamar102;
    private javax.swing.JPanel kamar103;
    private javax.swing.JPanel kamar104;
    private javax.swing.JPanel kamar105;
    private javax.swing.JPanel kamar106;
    private javax.swing.JPanel kamar107;
    private javax.swing.JPanel kamar108;
    private javax.swing.JPanel kamar109;
    private javax.swing.JPanel kamar201;
    private javax.swing.JPanel kamar202;
    private javax.swing.JPanel kamar203;
    private javax.swing.JPanel kamar204;
    private javax.swing.JPanel kamar205;
    private javax.swing.JPanel kamar206;
    private javax.swing.JPanel kamar207;
    private javax.swing.JPanel kamar208;
    private javax.swing.JPanel kamar209;
    private javax.swing.JPanel kamar301;
    private javax.swing.JPanel kamar302;
    private javax.swing.JPanel kamar303;
    private javax.swing.JPanel kamar304;
    private javax.swing.JPanel kamar305;
    private javax.swing.JPanel kamar306;
    private javax.swing.JPanel kamar307;
    private javax.swing.JPanel kamar308;
    private javax.swing.JPanel kamar309;
    private javax.swing.JPanel kamar401;
    private javax.swing.JPanel kamar402;
    private javax.swing.JPanel kamar403;
    private javax.swing.JPanel kamar404;
    private javax.swing.JPanel kamar405;
    private javax.swing.JPanel kamar406;
    private javax.swing.JPanel kamar407;
    private javax.swing.JPanel kamar408;
    private javax.swing.JPanel kamar409;
    // End of variables declaration//GEN-END:variables
}
